name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Triggers on semver tags like v1.0.0

jobs:
  maven_publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Extract Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish to MavenCentral
        # Uses the env variable set above to pass -Pversion=1.0.0
        # --no-configuration-cache: https://github.com/gradle/gradle/issues/22779
        run: ./gradlew -Pversion=${{ env.VERSION }} --no-configuration-cache --no-daemon publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: true
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

  gh_release:
    name: Create GitHub Release
    needs: maven_publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # github.ref_name is the tag (e.g., 'v1.0.0')
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

  update_readme:
    name: Update project version in README
    needs: maven_publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main # <--- Important: Checkout main, not the tag

      - name: Update Version in README
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          SCRIPT="s/(jecnaapi(-java)?:|<version>)([0-9]+\.[0-9]+\.[0-9]+)/\1$VERSION/"
          sed -i -E $SCRIPT README.md
          sed -i -E $SCRIPT README_en.md

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update library version in README to ${{ github.ref_name }}"
          branch: main
          file_pattern: README.md
